### ISSUE TITLE
Deploy build

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-demo#27]
Build a version of the demo and deploy it on IPFS. Once ready, we will publish it so that demo.chlu.io loads that build

**Comment by fazo96** [comment]
Looks like the build fails because of https://github.com/ipld/js-cid/issues/38

I'll see what the best workaround is

**Comment by fazo96** [comment]
We made a test build: http://ipfs.io/ipfs/Qmd3P3hmXxrwnT3zyon1JXkTZEmG5JctKBFyT8G5Vvp2he/

**Comment by fazo96** [comment]
So the build fails due to 

@kulpreet I am looking at all the options to solve this. Here is what we can do:

Short Term:

- use this ugly trick https://github.com/facebookincubator/create-react-app/issues/2108#issuecomment-347623672
- finishing and merging https://github.com/ChluNetwork/chlu-ipfs-support/pull/19 then importing that build instead of the babel transpiled sources
- finishing and merging #28, but this is only in case the others don't work because it requires ejecting

Long Term:

- react-scripts 2.0 will use uglify-es instead of uglify solving this problem completely. The change is already implemented in the alpha, it will also support targeting older browsers which will take care of compiling subdependencies of ipfs automatically

**Comment by kulpreet** [comment]
- [ ] setup subdomain demo
- [ ]  dns link to server demo from ipfs hash
- [ ] provide a deploy script - which ```npm run deploy``` - which runs ```ipns publish```  and voila

**Comment by fazo96** [comment]
The IPFS ID of the node we are running on EC2 is `QmYkctX9Wg5g2mBD8mnnNiCQE5toy3RqAkmzAmGEXY4dVU`

this means that `dnslink=/ipns/QmYkctX9Wg5g2mBD8mnnNiCQE5toy3RqAkmzAmGEXY4dVU` is what needs to be stored into the `TXT` record for the domain. The `A` records need to point to IPFS gateway(s) reachable on port 80, we can use the public ones without any issues.

When we want to update the demo we just need to publish a new version using IPNS from the EC2 and that's it. We can backup the private key so that we don't risk losing access to making new publications.

When I was making the first build I created chlu.ydns.eu to try out the `dnslink` functionality, and it still works even though it's an old build and does not use IPNS or HTTPS

@kulpreet can you set up the domains and the `dnslink`? I can work on the deploy script in the meantime

Another thing to consider: we need to use hashHistory I think. I'll make a couple of tests to see if browserHistory works but I suspect it won't

**Comment by fazo96** [comment]
New build: https://ipfs.io/ipfs/QmawsKKMeLy1mLQFh8YQaQnMV4GQQfr3GFzgvNuUeFc3sM

This is based on commit d994d1d47e5d2210d1f868bdfaa27829fc82714b from PR #52

**Comment by fazo96** [comment]
New build: https://ipfs.io/ipfs/QmYsqputTd3v84nEDKkgTN34ePuM5CZxM49yCPh8Hv5MFA

This is based on master as of now with a small change that disables all rendezvous servers except `ws-star-signal-2`
