### ISSUE TITLE
Saving reviews on IPFS

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-demo#42]
- [ ] Compute review record hash
- [ ] Set the review record hash in ```create_chlu_transaction#create``` where it is used in chlu-demo
- [ ] Once the transaction has been sent to the blockcypher api, then publish the review on IPFS

**Comment by fazo96** [comment]
@kulpreet we also have https://github.com/ChluNetwork/chlu-ipfs-support/issues/24 which kinda duplicates this, do we want to write to the blockchain from chlu-demo or from chlu-ipfs-support?

At the moment chlu-demo calls chlu-ipfs-support to store the review then it creates the blockchain transaction if the review was stored correctly in IPFS

We have to store the review to IPFS before we create the transaction since the IPFS multihash needs to go into the blockchain. I think it makes more sense to keep blockchain stuff out of chlu-ipfs-support and into chlu-wallet-support-js right?
