### ISSUE TITLE
When a customer creates or updates a review, they need to sign it with their private key

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-demo#53]
This change captures our move away from using IPNS. There's a few things that need to happen. We can split this issue up, but for now I am describing it here.

- [x] Generate a key pair for customer when the customer wallet is created
- [x] Publish the public key on IPFS
- [x] service nodes should pin this key
- [x] Include the public key cid in the Review Record
- [x] Sign RR hash with the secret key every time the customer creates or edits a review
- [ ] We will need to make sure we export this key pair as well from the customer wallet

This relates to how you have put in the validation that the review edit is being made by the same customer who created the first review.

**Comment by fazo96** [comment]
When a customer updates a review, he writes to his orbitDb which only he can write to, because other nodes will refuse writes not signed using the right key. The original RR has the orbitDb address which internally specifies which user can update the review.

I just realized the issue https://github.com/ChluNetwork/chlu-ipfs-support/issues/45 does not make sense because when checking for updates we read from the orbitDb address specified in the RR so only the updates from the original user will count

**Comment by fazo96** [comment]
Reporting from our slack thread in Feb 27: We decided to implement this even though orbitDb is already there to validate updates because:

- we might move away from orbitDb and we would be left without any system to validate updates
- we might use a single orbitDb in the future and handle validation on our level while allowing anyone to write to the orbitDb, by implementing custom rules

**Comment by fazo96** [comment]
Partially implemented in https://github.com/ChluNetwork/chlu-ipfs-support/issues/59

**Comment by fazo96** [comment]
Closed, the missing import/export issue has been moved to #61
